### ISSUE TITLE
Environment variables should be read using env-var and dotenv

### ISSUE THREAD

**Issue by hejkerooo** [pietrzakadrian/bank#1]
Dotenv lets you easily load env. variables
env-var got a great validation for them, instead of `parseInt` etc

**Comment by pietrzakadrian** [comment]
I solved this problem by removing the env file include from all redux-saga files

**Comment by hejkerooo** [comment]
I'm speaking about backend application

**Comment by pietrzakadrian** [comment]
done (actually branch 1.1)
