### ISSUE TITLE
return next, instead of false

### ISSUE THREAD

**Issue by hejkerooo** [pietrzakadrian/bank#10]
https://github.com/pietrzakadrian/bank/blob/4e7d378644edc76bc7e6b039004d52ed103fb1f5/server/middlewares/checkToken.middleware.js#L11

Do `return next();`

**Comment by pietrzakadrian** [comment]
done
https://github.com/pietrzakadrian/bank/commit/4219cad3605b1a75234cea7fb364ea0197d690b1
