### ISSUE TITLE
Feature request: backend on prisma.io

### ISSUE THREAD

**Issue by Fi1osof** [pietrzakadrian/bank#14]
Hi! Nice job! :)

Do you think about use https://www.prisma.io/ for backend? All in one (many databases provider, GraphQL schema-first architecture, WS subscriptions and etc.). 
Success using example: https://github.com/ian13456/mc.js

**Comment by pietrzakadrian** [comment]
Hello Fi1osof,
Thanks for recommending another technology.

I will keep the current stack because my goal was to learn rest api and associations in MySQL. However, maybe I will use GraphQL and prisma.io in my next project. :)
