### ISSUE TITLE
Default account pin and access code for login

### ISSUE THREAD

**Issue by thangchung** [pietrzakadrian/bank#16]
This application is great, but I just wonder where can I find the default account pin and access code to login to the demo site at https://bank.pietrzakadrian.com/login

**Comment by freedmo** [comment]
[config.ts](https://github.com/pietrzakadrian/bank/blob/1.1/backend/src/config/config.ts)
You can take or other values:
Account pin: 9922
Access code: root

**Comment by pietrzakadrian** [comment]
For security reasons the data on the demo page has been changed.
U can register new account in a few secounds: https://bank.pietrzakadrian.com/register

**Comment by freedmo** [comment]
But why not creating demo account ?
