### ISSUE TITLE
Error logging in user

### ISSUE THREAD

**Issue by giantthinker** [pietrzakadrian/bank#20]
Getting this log from the console
error: [middlewares:genericErrorHandler.middleware] Error: {"success":false,"code":400,"error":{}}

**Comment by pietrzakadrian** [comment]
I just downloaded the repository and install all dependencies using instruction in readme.
1) First I run the serwer, then I build the frontend.
2) I register new user and when I try to login, everything is successful.

Make sure you enter the correct information.

**Comment by giantthinker** [comment]
I entered the correct information so many times and still get the same problem. What does the error code mean?

**Comment by pietrzakadrian** [comment]
I will try to reproduce your problem. I will come back to you with an answer

**Comment by giantthinker** [comment]
Okay thank you.

**Comment by giantthinker** [comment]
Hi @pietrzakadrian any update?

**Comment by pietrzakadrian** [comment]
I don't see any mistake. Check your server settings
