### ISSUE TITLE
Column length too big for column

### ISSUE THREAD

**Issue by vbvjain** [pietrzakadrian/bank#25]
Hi, After running the backend for the first time using the watch script, I am getting the following -   QueryFailedError: ER_TOO_BIG_FIELDLENGTH: Column length too big for column 'accountBalanceHistory' (max = 16383); use BLOB or TEXT instead. I am running mysql Ver 8.0.20 for macos10.15.

**Comment by pietrzakadrian** [comment]
Hi. I know this error.
At the moment I am working on version 2.0 of the application.
I have little work left, so you can check out these repositories:

https://github.com/pietrzakadrian/bank-client
https://github.com/pietrzakadrian/bank-server

**Comment by pietrzakadrian** [comment]
Bank Application v2.0 is ready. https://bank.pietrzakadrian.com/
Working client and server repositories can be found above.
I will continue to develop it, so stay tuned.
