### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Neustradamus** [pietrzakadrian/bank#26]
The website is down, can you solve it?

**Comment by pietrzakadrian** [comment]
Hi, I know about this problem.
I had to reinstall my vps with the ubuntu server system to properly install the required dependencies for bank application 2.0 (new version).

I need a few more days to finish my project. When I'm done, the new version will appear on the current page (bank.pietrzakadrian.com)

**Comment by pietrzakadrian** [comment]
The site is already working. I installed the 2.0 software version on it.
I will regularly update there because the application will be developed.

https://bank.pietrzakadrian.com/

**Comment by mutza974** [comment]
> The website is down, can you solve it?
