### ISSUE TITLE
Extract data layer

### ISSUE THREAD

**Issue by hejkerooo** [pietrzakadrian/bank#9]
All functionalities responsible for pulling data from any source should be done in the proper layer - in that case, data layer. If you would switch to the different solution (for ex. mongoose/typeorm) you won't have to worry about refactoring half of the application.

```javascript
export class UserRepository {
	findOrThrow(userId) { }...
	getUserStatus(userId) { }...
}
```

**Comment by pietrzakadrian** [comment]
I definitely want to use MySQL for this project so I think, that typeORM is a good choose.
I'm just in the process of rewriting my application and I'm wondering what technology to use for the backend.

I was thinking about use the Symfony PHP framework, but I want to stay with NodeJS, so rather I will decide to use TypeORM and TypeScript.

**Comment by pietrzakadrian** [comment]
done.
https://github.com/pietrzakadrian/bank/blob/1.1/backend/src/services/users.service.ts
